# SPDX-License-Identifier: Apache-2.0
---
namespace: sentenz
name: observability
version: "1.0.0"
authors:
  - sentenz
readme: README.md
description: >-
  Ansible Collection for Observability.
license:
  - Apache-2.0
repository: ""
tags:
  - observability
  - monitoring
  - linux
