# SPDX-License-Identifier: Apache-2.0
---
collections:
  - name: sentenz.common
    src: ./collections/ansible_collections/sentenz/common
    type: subdirs
  - name: sentenz.reverse_proxy
    src: ./collections/ansible_collections/sentenz/reverse_proxy
    type: subdirs
  - name: sentenz.observability
    src: ./collections/ansible_collections/sentenz/observability
    type: subdirs
  - name: sentenz.component_analysis
    src: ./collections/ansible_collections/sentenz/component_analysis
    type: subdirs
