# SPDX-License-Identifier: Apache-2.0
---
collections:
  - name: sentenz.container
    src: ./collections/ansible_collections/sentenz/container
    type: subdirs
  - name: sentenz.observability
    src: ./collections/ansible_collections/sentenz/observability
    type: subdirs
  - name: sentenz.component_analysis
    src: ./collections/ansible_collections/sentenz/component_analysis
    type: subdirs
