# SPDX-License-Identifier: Apache-2.0
---
- name: Deploy Observability
  import_playbook: playbooks/observability.yml

- name: Deploy Component Analysis
  import_playbook: playbooks/component-analysis.yml
