{
 "title": "Logs",
 "tags": [
  "loki",
  "linux"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   { "name": "label_name", "label": "Label Name", "query": "label_names()" },
   { "name": "label_value", "label": "Label Value", "query": "label_values($label_name)" },
   {
    "name": "job",
    "label": "Job",
    "query": {}
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Insights",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Logs",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "expr": "count by(instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} [$__interval]))"
      }
     ]
    },
    {
     "title": "Total Error Logs",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "expr": "count by(instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} |~ \"(?i)(error|fatal|critical)\" | __error__=\"\" [$__interval]))"
      }
     ]
    },
    {
     "title": "Total Warn Logs",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "expr": "count by(instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} |~ \"(?i)(warn)\" [$__interval]))"
      }
     ]
    },
    {
     "title": "Total Debug Logs",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "expr": "count by(instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} |~ \"(?i)(debug)\" [$__interval]))"
      }
     ]
    },
    {
     "title": "Error Logs",
     "type": "logs",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} |~ \"(?i)(error|fatal|critical)\" | __error__=\"\" | logfmt"
      }
     ]
    },
    {
     "title": "Warn Logs",
     "type": "logs",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} |~ \"(?i)(warn)\" | logfmt"
      }
     ]
    },
    {
     "title": "Debug Logs",
     "type": "logs",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} |~ \"(?i)(debug)\" | logfmt"
      }
     ]
    },
    {
     "title": "Info Logs",
     "type": "logs",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} |~ \"(?i)(info)\" | logfmt"
      }
     ]
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error Log in Bytes",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "bytes_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} |~ \"(?i)(error|fatal|critical)\" | __error__=\"\" [$__interval])",
       "legendFormat": "{{ container }}"
      }
     ]
    },
    {
     "title": "Error Log in Bytes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 18, "x": 6, "y": 2 },
     "targets": [
      {
       "expr": "bytes_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} |~ \"(?i)(error|fatal|critical)\" | __error__=\"\" [$__interval])",
       "legendFormat": "{{ container }}"
      }
     ]
    },
    {
     "title": "Warn Log in Bytes",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "bytes_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} |~ \"(?i)(warn)\" [$__interval])",
       "legendFormat": "{{ container }}"
      }
     ]
    },
    {
     "title": "Warn Log in Bytes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 18, "x": 6, "y": 11 },
     "targets": [
      {
       "expr": "bytes_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} |~ \"(?i)(warn)\" [$__interval])",
       "legendFormat": "{{ container }}"
      }
     ]
    },
    {
     "title": "Debug Log in Bytes",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "bytes_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} |~ \"(?i)(debug)\" [$__interval])",
       "legendFormat": "{{ container }}"
      }
     ]
    },
    {
     "title": "Debug Log in Bytes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 18, "x": 6, "y": 20 },
     "targets": [
      {
       "expr": "bytes_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} |~ \"(?i)(debug)\" [$__interval])",
       "legendFormat": "{{ container }}"
      }
     ]
    }
   ]
  }
 ]
}