{
 "title": "USE Method",
 "description": "The USE Method based on Node Dashboard for the Prometheus Node Exporter",
 "tags": [
  "use",
  "node",
  "prometheus"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Utilisation",
     "type": "timeseries",
     "description": "CPU Busy\n\nThe fraction of time that the CPU is busy. A high percentage (close to 100%) indicates that the system is running low on available CPU resources.",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\",mode=\"idle\"}[$__rate_interval])) * 100)",
       "legendFormat": "CPU Busy"
      }
     ]
    },
    {
     "title": "CPU Saturation",
     "type": "timeseries",
     "description": "System Load\n\nThe degree to which the extra workload will be queued using load averages as a proxy.\n\nLoad Average\n\nThe metric represents the n-minute load average. The load average is the average number of jobs in the run queue (state R) or waiting for disk I/O (state D) over the last n-minutes.\n\nRun Queue Length\n\nThe number of tasks in the runnable or uninterruptible state. A high run queue length can indicate CPU saturation.\n\nCPU I/O Wait\n\nThe amount of time the CPU is idle due to waiting to handle I/O operations. High I/O wait times can indicate CPU saturation.",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_load1{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Load 1"
      },
      {
       "expr": "node_procs_running{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Run Queue Length"
      },
      {
       "expr": "sum(rate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\",mode=\"iowait\"}[$__rate_interval]))",
       "legendFormat": "CPU I/O Wait"
      },
      {
       "expr": "count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))",
       "legendFormat": "CPU Cores"
      }
     ]
    },
    {
     "title": "CPU Error",
     "type": "timeseries",
     "description": "NOTE The metrics are just proxies for errors and may not indicate an actual error state. Always interpret these metrics in the context of the system performance and other indicators.\n\nContext Switches\n\nThe metric represents the total number of context switches. A context switch is the action of storing the state of a process or of a thread so that execution can be resumed from the same point at a later time. High rates of context switching can indicate inefficient scheduling or  contention for CPU resources.\n\nSteal Time\n\nIn virtualized environments, \"steal time\" refers to the time that a virtual CPU waits for a real CPU while the hypervisor is servicing another virtual processor.\n\nSoft Lockups\n\nA soft lockup is the symptom of a task or kernel thread using and not releasing a CPU for a period of time.\n\nGuest Time\n\nIn virtualized environments, this refers to the time a CPU was busy executing a virtual CPU for guest operating systems under the control of the Linux kernel.\n",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(node_context_switches_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Context Switches"
      },
      {
       "expr": "sum(rate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\",mode=\"steal\"}[$__rate_interval]))",
       "legendFormat": "Steal Time"
      },
      {
       "expr": "sum(rate(node_softnet_times_squeezed_total{instance=\"$node\",job=\"$job\"}[$__rate_interval]))",
       "legendFormat": "Soft Lockups"
      },
      {
       "expr": "sum(rate(node_cpu_guest_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval]))",
       "legendFormat": "Guest Time"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Utilisation",
     "type": "timeseries",
     "description": "RAM\n\nThe fraction of time that the memory is being used. A high demand (close to 100%) indicates that the system is running low on available memory.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"} - (node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node\",job=\"$job\"})",
       "legendFormat": "RAM Used"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "RAM Total"
      }
     ]
    },
    {
     "title": "Memory Saturation",
     "type": "timeseries",
     "description": "SWAP\n\nThe degree to which the extra workload will be queued using swap usage as a proxy. The metric represents the number of memory pages that have been read/written from the swap space into the memory. Consistently high values for this metric could indicate that the system is under memory pressure.\n\nMemory Buffer Size\n\nIf the buffer size is decreasing, it could indicate memory pressure.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_SwapTotal_bytes{instance=\"$node\", job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\", job=\"$job\"}",
       "legendFormat": "SWAP Used"
      },
      {
       "expr": "node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "SWAP Total"
      }
     ]
    },
    {
     "title": "Memory Error",
     "type": "timeseries",
     "description": "OOM Killer\n\nThe Out-Of-Memory (OOM) killer is a process that the Linux kernel employs when the system is critically low on memory. Values consistently above zero, means the system is frequently running out of memory. System kills of processes due to insufficient memory, it's a strong indicator of memory errors.\n\nMemory Page Faults\n\nThe number of major faults the system has made due to the fact that not enough memory was available, resulting in disk swap in/out operations. This is often a symptom of the system not having enough memory, which can be considered a form of memory error.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(node_vmstat_oom_kill{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "OOM Killer"
      },
      {
       "expr": "rate(node_vmstat_pgmajfault{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Memory Page Faults"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Network Utilisation",
     "type": "timeseries",
     "description": "Traffic Bandwidth\n\nThe metric is a counter that represents the total number of bytes received/transmitted on the network interface. High rates can indicate that the network interface is heavily utilized.\n\nPacket Rate\n\nThe rate of packets sent or received can be indicative of network utilization.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_transmit_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])) + sum(rate(node_network_receive_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval]))",
       "legendFormat": "Traffic Bandwidth"
      }
     ]
    },
    {
     "title": "Network Saturation",
     "type": "timeseries",
     "description": "Receive/Transmit Drop\n\nThe metric is a counter that represents the total number of received/transmitted packets that were dropped. Dropped packets could indicate network saturation.\n\nTransmit Queue Length\n\nIndicates if the network interface is saturated. A growing queue length can indicate higher saturation levels.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_drop_total{instance=\"$node\",job=\"$job\"}[$__rate_interval]))",
       "legendFormat": "Receive Drop {{device}}"
      },
      {
       "expr": "sum(rate(node_network_transmit_drop_total{instance=\"$node\",job=\"$job\"}[$__rate_interval]))",
       "legendFormat": "Transmit Drop {{device}}"
      }
     ]
    },
    {
     "title": "Network Error",
     "type": "timeseries",
     "description": "Receive/Transmit Errors\n\nThe metric is a counter that represents the total number of receive/transmit errors encountered by the network device. The errors could be due to various reasons such as faulty hardware, network congestion, or packet corruption. Error counts can be a sign of network problems.",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_errs_total{instance=\"$node\",job=\"$job\"}[$__rate_interval]))",
       "legendFormat": "Receive Errors {{device}}"
      },
      {
       "expr": "sum(rate(node_network_transmit_errs_total{instance=\"$node\",job=\"$job\"}[$__rate_interval]))",
       "legendFormat": "Transmit Errors {{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Disk I/O Utilisation",
     "type": "timeseries",
     "description": "I/O Busy\n\nThe metric represents the total number of seconds spent doing I/O operations. A high rate indicates that the system is spending a lot of time performing disk I/O operations, which could be a sign of a bottleneck.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_io_time_seconds_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval]))",
       "legendFormat": "I/O Busy {{device}}"
      }
     ]
    },
    {
     "title": "Disk I/O Saturation",
     "type": "timeseries",
     "description": "NOTE The metrics are just proxies for saturation and may not indicate an actual saturation state. Always interpret these metrics in the context of the system performance and other indicators.\n\nI/O Wait Time\n\nThe time operations had to wait for disk access.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\",mode='iowait'}[$__rate_interval])) / sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])) * 100",
       "legendFormat": "I/O Wait Time {{device}}"
      }
     ]
    },
    {
     "title": "Disk I/O Error",
     "type": "timeseries",
     "description": "NOTE The metrics are just proxies for errors and may not indicate an actual error state. Always interpret these metrics in the context of the system performance and other indicators.\n\nI/O Queue Operations\n\nThe number of queued operations that are waiting to be completed represented as the number of read/write errors.",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(node_disk_io_now{instance=\"$node\",job=\"$job\"})",
       "legendFormat": "I/O Queue Operations {{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Storage Utilisation",
     "type": "timeseries",
     "description": "Disk Space\n\nThe metric provides the number of bytes available in the filesystem. It shows how much free space is left that can be utilized.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} - node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}",
       "legendFormat": "Disk Space Used"
      },
      {
       "expr": "node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}",
       "legendFormat": "Disk Space Total"
      }
     ]
    },
    {
     "title": "Storage Saturation",
     "type": "timeseries",
     "description": "NOTE The metrics are just proxies for saturation and may not indicate an actual saturation state. Always interpret these metrics in the context of the system performance and other indicators.\n\nFile Nodes\n\nThe metric indicates the number of free inodes in the filesystem. Inodes are data structures used to store information about files and directories.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_filesystem_files{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} - node_filesystem_files_free{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}",
       "legendFormat": "File Nodes Used"
      },
      {
       "expr": "node_filesystem_files{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}",
       "legendFormat": "File Nodes Total"
      }
     ]
    },
    {
     "title": "Storage Error",
     "type": "timeseries",
     "description": "NOTE The metrics are just proxies for errors and may not indicate an actual error state. Always interpret these metrics in the context of the system performance and other indicators.\n\nDisk Filesystem Error\n\nThe metric counts the number of errors encountered by the filesystem device. Errors can occur due to various reasons such as hardware issues, permission problems, or configuration errors.",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_filesystem_device_error{instance=\"$node\",job=\"$job\",device!~'rootfs',fstype!~'tmpfs'}",
       "legendFormat": "Disk Filesystem Error - {{mountpoint}}"
      }
     ]
    }
   ]
  }
 ]
}