# SPDX-License-Identifier: Apache-2.0
---
all:
  children:
    observability:
      hosts:
        staging.observability.dev: 
    component_analysis:
      hosts:
        staging.component-analysis.dev: 
