# SPDX-License-Identifier: Apache-2.0
---
all:
  children:
    local:
      hosts:
        localhost:
    observability:
      hosts:
        observability.localhost: 
    component_analysis:
      hosts:
        component-analysis.localhost: 
