# SPDX-License-Identifier: Apache-2.0
---
- name: Traefik - Restart Docker Compose
  listen: traefik_restart
  community.docker.docker_compose_v2:
    project_src: "{{ traefik_path }}"
    files:
      - docker-compose.yml
    state: restarted
