# SPDX-License-Identifier: Apache-2.0
---
- name: Traefik | Restart Docker Compose
  listen: traefik_restart
  community.docker.docker_compose_v2:
    project_src: "{{ traefik_path }}"
    files:
      - docker-compose.yml
    state: restarted
  when:
    - traefik_state == 'present'
    - traefik_compose_file.stat.exists | default(false)
