# SPDX-License-Identifier: Apache-2.0
---
- name: Traefik - Recreate containers and wait for health
  listen: traefik_restart
  community.docker.docker_compose_v2:
    project_src: "{{ traefik_path }}"
    files: [docker-compose.yml]
    docker_cli: "{{ traefik_docker_cli }}"
    state: present
    recreate: always
    pull: missing
    wait: true
    wait_timeout: "{{ traefik_wait_timeout }}"
  when: not ansible_check_mode
  no_log: true

- name: Traefik - Stop Docker Compose
  listen: traefik_stop
  community.docker.docker_compose_v2:
    project_src: "{{ traefik_path }}"
    files: [docker-compose.yml]
    docker_cli: "{{ traefik_docker_cli }}"
    state: stopped
  no_log: true

- name: Traefik - Remove Docker Compose
  listen: traefik_absent
  community.docker.docker_compose_v2:
    project_src: "{{ traefik_path }}"
    files: [docker-compose.yml]
    docker_cli: "{{ traefik_docker_cli }}"
    state: absent
    remove_volumes: false
  no_log: true
