# SPDX-License-Identifier: Apache-2.0
---
namespace: sentenz
name: common
version: "1.0.0"
authors:
  - sentenz
readme: README.md
description: >-
  Ansible Collection for Common.
license:
  - Apache-2.0
repository: ""
tags:
  - aws
  - container
  - linux
