# SPDX-License-Identifier: Apache-2.0
---
# Reverse Proxy
traefik_name: traefik
traefik_path: /etc/ansible_collections/reverse_proxy/traefik
traefik_networks: []

# Reverse Proxy Traefik
traefik_image: traefik:latest
traefik_ports: []
traefik_acme_email: your-email@example.com
traefik_acme_storage: /letsencrypt/acme.json
traefik_certificates_resolver: myresolver
traefik_challenge_dns_provider: cloudflare
traefik_challenge_dns_provider_variables: []

# Files
traefik_acme_config: acme.json
traefik_dynamic_config: dynamic.yml
traefik_tls_private_key: certs/key.pem
traefik_tls_public_cert: certs/cert.pem

# Paths
traefik_certs_path: "{{ traefik_path }}/certs"
traefik_dynamic_config_path: /etc/traefik/dynamic/

# Reverse Proxy Traefik HTTPS Challenge
# Choices: http, dns, tls, intranet, debug
traefik_challenge: debug

traefik_challenge_http:
  - --entryPoints.web.address=:80
  - --entryPoints.websecure.address=:443
  - --certificatesresolvers.{{ traefik_certificates_resolver }}.acme.httpchallenge=true
  - --certificatesresolvers.{{ traefik_certificates_resolver }}.acme.httpchallenge.entrypoint=web
  - --certificatesresolvers.{{ traefik_certificates_resolver }}.acme.email={{ traefik_acme_email }}
  - --certificatesresolvers.{{ traefik_certificates_resolver }}.acme.storage={{ traefik_acme_storage }}

traefik_challenge_http_router:
  name: service
  domain: localhost
  certresolver: "{{ traefik_certificates_resolver }}"
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.{{ traefik_name }}.rule=Host(`localhost`)"
    - "traefik.http.routers.{{ traefik_name }}.entrypoints=websecure"
    - "traefik.http.routers.{{ traefik_name }}.tls=true"
    - "traefik.http.routers.{{ traefik_name }}.tls.certresolver={{ traefik_certificates_resolver }}"

traefik_challenge_dns:
  - --entryPoints.web.address=:80
  - --entryPoints.websecure.address=:443
  - --certificatesresolvers.{{ traefik_certificates_resolver }}.acme.dnschallenge=true
  - --certificatesresolvers.{{ traefik_certificates_resolver }}.acme.dnschallenge.provider={{ traefik_challenge_dns_provider }}
  - --certificatesresolvers.{{ traefik_certificates_resolver }}.acme.email={{ traefik_acme_email }}
  - --certificatesresolvers.{{ traefik_certificates_resolver }}.acme.storage={{ traefik_acme_storage }}

traefik_challenge_dns_router:
  name: service
  domain: localhost
  certresolver: "{{ traefik_certificates_resolver }}"
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.{{ traefik_name }}.rule=Host(`localhost`)"
    - "traefik.http.routers.{{ traefik_name }}.entrypoints=websecure"
    - "traefik.http.routers.{{ traefik_name }}.tls=true"
    - "traefik.http.routers.{{ traefik_name }}.tls.certresolver={{ traefik_certificates_resolver }}"

traefik_challenge_tls:
  - --entryPoints.websecure.address=:443
  - --certificatesresolvers.{{ traefik_certificates_resolver }}.acme.tlschallenge=true
  - --certificatesresolvers.{{ traefik_certificates_resolver }}.acme.email={{ traefik_acme_email }}
  - --certificatesresolvers.{{ traefik_certificates_resolver }}.acme.storage={{ traefik_acme_storage }}

traefik_challenge_tls_router:
  name: service
  domain: localhost
  certresolver: "{{ traefik_certificates_resolver }}"
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.{{ traefik_name }}.rule=Host(`localhost`)"
    - "traefik.http.routers.{{ traefik_name }}.entrypoints=websecure"
    - "traefik.http.routers.{{ traefik_name }}.tls=true"
    - "traefik.http.routers.{{ traefik_name }}.tls.certresolver={{ traefik_certificates_resolver }}"

traefik_challenge_debug:
  - --entrypoints.web.address=:80
  - --entrypoints.websecure.address=:443
  - --entrypoints.websecure.http.tls=true
  - --entrypoints.web.http.redirections.entryPoint.to=websecure
  - --entrypoints.web.http.redirections.entryPoint.scheme=https
  - --providers.file.directory={{ traefik_dynamic_config_path }}
  - --providers.file.watch=true

traefik_challenge_debug_router:
  name: service
  domain: localhost
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.{{ traefik_name }}.rule=Host(`localhost`)"
    - "traefik.http.routers.{{ traefik_name }}.entrypoints=websecure"
    - "traefik.http.routers.{{ traefik_name }}.tls=true"

traefik_challenge_options: []
