# SPDX-License-Identifier: Apache-2.0
---
namespace: sentenz
name: dependency_track
version: "1.0.2"
authors:
  - sentenz
readme: README.md
description: >-
  Ansible Collection for OWASP Dependency-Track.
license:
  - Apache-2.0
repository: ""
tags:
  - sca
